#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists. Delete it first if you want to regenerate: rm $ENV_FILE"
  exit 0
fi

GARAGE_ACCESS_KEY="GK$(openssl rand -hex 16)"
GARAGE_SECRET_KEY="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — keep this file secret!
JWT_SECRET=$JWT_SECRET

# Garage S3-compatible storage
S3_BUCKET=openshelf
GARAGE_ACCESS_KEY=$GARAGE_ACCESS_KEY
GARAGE_SECRET_KEY=$GARAGE_SECRET_KEY

# Optional: custom domain for Caddy HTTPS
# DOMAIN=books.example.com
EOF

echo "Created .env with generated secrets."
echo
echo "Access key: $GARAGE_ACCESS_KEY"
echo "Secret key: $GARAGE_SECRET_KEY"
echo
echo "Run: docker compose up -d"
