#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists. Delete it first if you want to regenerate: rm $ENV_FILE"
  exit 0
fi

JWT_SECRET="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh: keep this file secret!
JWT_SECRET=$JWT_SECRET

# Cloudflare R2 (S3-compatible storage)
# Fill these in from your R2 dashboard:
R2_ACCOUNT_ID=
S3_BUCKET=openshelf
S3_ACCESS_KEY=
S3_SECRET_KEY=

# Optional: custom domain for Caddy HTTPS
# DOMAIN=books.example.com
EOF

echo "Created .env with JWT_SECRET."
echo ""
echo "Now edit .env and fill in your R2 credentials:"
echo "  nano .env"
echo ""
echo "Then: docker compose up -d"
